networks:
  traefik-jellyfin:
    name: traefik-jellyfin
    internal: true
  traefik-pihole:
    name: traefik-pihole
    internal: true
  traefik-qbittorrent:
    name: traefik-qbittorrent
    internal: true
  traefik-arcane-agent:
    name: traefik-arcane-agent
    internal: true
  traefik-couchdb:
    name: traefik-couchdb
    internal: true
  traefik-forgejo:
    name: traefik-forgejo
    internal: true