services:
  server:
    image: owncloud/server:10.15

    security_opt:
      - no-new-privileges:true

    restart: unless-stopped
    healthcheck:
      test: ["CMD", "/usr/bin/healthcheck"]
      interval: 30s
      timeout: 10s
      retries: 5

    depends_on:
      - mariadb
      - redis

    environment:
      - OWNCLOUD_DOMAIN=${OWNCLOUD_WEB_HOST}
      - OWNCLOUD_TRUSTED_DOMAINS=${OWNCLOUD_WEB_HOST}
      - OWNCLOUD_DB_TYPE=mysql
      - OWNCLOUD_DB_NAME=owncloud
      - OWNCLOUD_DB_USERNAME=owncloud
      - OWNCLOUD_DB_PASSWORD=owncloud
      - OWNCLOUD_DB_HOST=mariadb
      # - OWNCLOUD_ADMIN_USERNAME=${ADMIN_USERNAME}
      # - OWNCLOUD_ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - OWNCLOUD_MYSQL_UTF8MB4=true
      - OWNCLOUD_REDIS_ENABLED=true
      - OWNCLOUD_REDIS_HOST=redis

    volumes:
      - ${OWNCLOUD_FILES_VOLUME}:/mnt/data

    networks:
      - traefik
      - internal
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.owncloud.rule=Host(`${OWNCLOUD_WEB_HOST}`)"
      - "traefik.http.routers.owncloud.entrypoints=websecure"
      - "traefik.http.routers.owncloud.tls=true"
      - "traefik.http.routers.owncloud.tls.certresolver=le"
      - "traefik.http.services.owncloud.loadbalancer.server.port=8080"

  mariadb:
    image: mariadb:10.11
    command: ["--max-allowed-packet=128M", "--innodb-log-file-size=64M"]

    security_opt:
      - no-new-privileges:true

    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-u", "root", "--password=owncloud"]
      interval: 10s
      timeout: 5s
      retries: 5

    environment:
      - MYSQL_ROOT_PASSWORD=owncloud
      - MYSQL_USER=owncloud
      - MYSQL_PASSWORD=owncloud
      - MYSQL_DATABASE=owncloud
      - MARIADB_AUTO_UPGRADE=1

    volumes:
      - ${OWNCLOUD_MARIADB_VOLUME}:/var/lib/mysql

    networks:
      - internal

  redis:
    image: redis:6
    command: ["--databases", "1"]

    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

    volumes:
      - ${OWNCLOUD_REDIS_VOLUME}:/data
    networks:
      - internal

networks:
  internal:
    driver: bridge
    internal: true
  traefik:
    external: true
