services:
  tailscale:
    image: ghcr.io/tailscale/tailscale:latest
    restart: unless-stopped
    environment:
      TS_HOSTNAME: ${TAILSCALE_HOSTNAME}
      TS_AUTHKEY: ${TAILSCALE_AUTHKEY}
      TS_STATE_DIR: /var/lib/tailscale
      TS_EXTRA_ARGS: --advertise-exit-node
    volumes:
      - ${TAILSCALE_STATE_VOLUME}:/var/lib/tailscale
    devices:
      - /dev/net/tun:/dev/net/tun
    network_mode: host
    security_opt:
      - no-new-privileges=true
    cap_add:
      - net_admin
      - net_raw
