services:
  tailscale:
    container_name: tailscale
    image: ghcr.io/tailscale/tailscale:latest
    restart: unless-stopped
    environment:
      TS_HOSTNAME: vps1
      TS_AUTHKEY: ${TAILSCALE_AUTHKEY:-}
      TS_STATE_DIR: /var/lib/tailscale
      TS_EXTRA_ARGS: --advertise-exit-node
      TS_USERSPACE: false
    volumes:
      - tailscale_state:/var/lib/tailscale
    devices:
      - /dev/net/tun:/dev/net/tun
    network_mode: host
    cap_add:
      - net_admin
      - net_raw

volumes:
  tailscale_state:
    name: tailscale_state
    driver: local
