entryPoints:
  websecure:
    http:
      tls:
        certResolcer: le

certificatesResolvers:
  le:
    acme:
      email: varma01@mail.com
      storage: /letsencrypt/acme.json
      httpChallenge:
        entryPoint: web
  ts:
    tailscale: {}
