include:
  - ../traefik/networks.compose.yaml

services:
  pihole:
    container_name: pihole
    image: ghcr.io/pihole/pihole:2025.11.0
    restart: unless-stopped
    ports:
      - "53:53"
    environment:
      TZ: Europe/Budapest
      FTLCONF_dns_listeningMode: ALL
    volumes:
      - pihole_config:/etc/pihole
    cap_add:
      - SYS_NICE
    networks:
      - traefik-pihole
      - internet
    labels:
      traefik.enable: true
      traefik.docker.network: traefik-pihole
      traefik.http.routers.pihole.rule: Host(`${PIHOLE_WEB_HOST}`)
      traefik.http.services.pihole.loadbalancer.server.port: 80
      traefik.http.routers.pihole.entrypoints: websecure

networks:
  internet:
    driver: bridge

volumes:
  pihole_config:
    name: pihole_config
    driver: local
