providers:
  docker:
    exposedByDefault: false
    watch: true
    network: traefik
  file:
    directory: /etc/traefik/dynamic

api:
  dashboard: true
  insecure: false

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: true

  websecure:
    address: ":443"
    http:
      tls:
        options: default
        certResolver: le

certificatesResolvers:
  le:
    acme:
      email: "contact+letsencrypt@varma01.dev"
      storage: "/acme/le.json"
      httpChallenge:
        entryPoint: web
  cf:
    acme:
      email: "contact+letsencrypt@varma01.dev"
      storage: "/acme/cf.json"
      dnsChallenge:
        provider: cloudflare
        delayBeforeCheck: 10

http:
  middlewares:
    tailnet-restricted:
      ipAllowList:
        sourceRange:
          - "100.64.0.0/10"

ping: {}

logs:
  level: INFO
  format: common
  filePath: "/var/log/traefik.log"