services:
  jellyfin:
    image: jellyfin/jellyfin:10.11
    security_opt:
      - no-new-privileges:true

    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Budapest
      - JELLYFIN_PublishedServerUrl=https://${JELLYFIN_HOST}

    volumes:
      - ${JELLYFIN_CONFIG_VOLUME}:/config
      - ${JELLYFIN_CACHE_VOLUME}:/cache
      - ${JELLYFIN_MEDIA_VOLUME}:/media
      - ${DONWLOADS_READONLY_VOLUME}:/downloads:ro

    restart: "unless-stopped"
    healthcheck:
      interval: 1m
      retries: 5
      start_interval: 5s
      start_period: 15s
      timeout: 5s
      test: "curl --fail http://localhost:8096/health || exit 1"

    networks:
      - traefik
      - internet
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jellyfin.rule=Host(`${JELLYFIN_HOST}`)"
      - "traefik.http.routers.jellyfin.entrypoints=websecure"
      - "traefik.http.routers.jellyfin.tls=true"
      - "traefik.http.routers.jellyfin.tls.certresolver=le"
      - "traefik.http.services.jellyfin.loadbalancer.server.port=8096"

networks:
  internet:
    driver: bridge
  traefik:
    external: true
