services:
  hbbs:
    container_name: rustdesk-hbbs
    image: ghcr.io/rustdesk/rustdesk-server:1.1.15
    command: hbbs
    depends_on:
      - hbbr
    restart: unless-stopped
    volumes:
      - rustdesk_data:/root
    ports:
      - 21115:21115/tcp
      - 21116:21116/tcp
      - 21116:21116/udp

  hbbr:
    container_name: rustdesk-hbbr
    image: ghcr.io/rustdesk/rustdesk-server:1.1.15
    command: hbbr
    restart: unless-stopped
    volumes:
      - rustdesk_data:/root
    ports:
      - 21117:21117/tcp

volumes:
  rustdesk_data:
    name: rustdesk_data
    driver: local
