services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Budapest
      - WEBUI_PORT=8080
      - TORRENTING_PORT=6881
    volumes:
      - ${QBTORRENT_CONFIG_VOLUME}:/config
      - ${QBTORRENT_DOWNLOADS_VOLUME}:/downloads
    # ports:
    # - 16881:6881
    # - 16881:6881/udp

    security_opt:
      - no-new-privileges:true

    restart: unless-stopped
    healthcheck:
      interval: 1m
      retries: 5
      start_interval: 5s
      start_period: 15s
      timeout: 5s
      test: "curl --fail http://localhost:80 || exit 1"

    networks:
      - traefik
      - internet
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.qbittorrent.rule=Host(`${QBTORRENT_WEB_HOST}`)"
      - "traefik.http.routers.qbittorrent.entrypoints=websecure"
      - "traefik.http.routers.qbittorrent.tls=true"
      - "traefik.http.routers.qbittorrent.tls.certresolver=cf"
      - "traefik.http.services.qbittorrent.loadbalancer.server.port=8080"

networks:
  internet:
    driver: bridge
  traefik:
    external: true
