services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:5.1.2

    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Budapest
      - WEBUI_PORT=8080
      - TORRENTING_PORT=6881
    volumes:
      - ${QBTORRENT_CONFIG_VOLUME}:/config
      - ${QBTORRENT_DOWNLOADS_VOLUME}:/downloads
    # ports:
    #   - 18081:8080
    #   - 16881:6881
    #   - 16881:6881/udp

    security_opt:
      - no-new-privileges:true

    restart: unless-stopped
    healthcheck:
      interval: 1m
      retries: 5
      start_interval: 5s
      start_period: 15s
      timeout: 5s
      test: "curl --fail http://localhost:8080 || exit 1"

    networks:
      - traefik
      - internet
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.qbittorrent.tls=true"
      - "traefik.http.routers.qbittorrent.entrypoints=websecure"
      - "traefik.http.routers.qbittorrent.tls.certresolver=cf"
      - "traefik.http.routers.qbittorrent.rule=Host(`${QBTORRENT_WEB_HOST}`)"
      - "traefik.http.services.qbittorrent.loadbalancer.server.port=8080"
      - "traefik.http.routers.qbittorrent.middlewares=tailnet-whitelist@file"

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Budapest
    volumes:
      - ${PROWLARR_CONFIG_VOLUME}:/config
    # ports:
    #   - 9696:9696

    restart: unless-stopped
    healthcheck:
      interval: 1m
      retries: 5
      start_interval: 5s
      start_period: 15s
      timeout: 5s
      test: "curl --fail http://localhost:9696 || exit 1"
    security_opt:
      - no-new-privileges:true

    networks:
      - internet
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.prowlarr.tls=true"
      - "traefik.http.routers.prowlarr.entrypoints=websecure"
      - "traefik.http.routers.prowlarr.tls.certresolver=cf"
      - "traefik.http.routers.prowlarr.rule=Host(`${PROWLARR_WEB_HOST}`)"
      - "traefik.http.services.prowlarr.loadbalancer.server.port=9696"
      - "traefik.http.routers.prowlarr.middlewares=tailnet-whitelist@file,authelia@file"

networks:
  internet:
    driver: bridge
  traefik:
    external: true
